import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';
import type { DailyLog, MonthlyReport, UserProfile } from '@/types';
import { format } from 'date-fns';

// Register Inter font
Font.register({
  family: 'Inter',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2emQ.ttf', fontWeight: 'normal' },
    { src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2emQ.ttf', fontWeight: 500 },
    { src: 'https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2emQ.ttf', fontWeight: 'bold' },
  ]
});

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Inter',
    padding: '1in',
    fontSize: 12,
    color: '#333',
  },
  header: {
    marginBottom: 30,
    textAlign: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
  },
  table: {
    display: "flex",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderColor: '#eee',
    marginBottom: 20,
  },
  tableRow: {
    flexDirection: "row",
    backgroundColor: '#fff',
  },
  tableColHeader: {
    width: "30%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#eee',
    backgroundColor: '#f8f8f8',
    padding: 8,
  },
  tableCol: {
    width: "70%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#eee',
    padding: 8,
  },
  tableCellHeader: {
    fontSize: 11,
    fontWeight: 'bold',
  },
  tableCell: {
    fontSize: 10,
    
  },
  logDateCell: {
    width: '30%',
    padding: 8,
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#eee',
  },
  logContentCell: {
    width: '70%',
    padding: 8,
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderColor: '#eee',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 10,
    color: 'grey',
  }
});

interface MonthlyReportDocumentProps {
  report: MonthlyReport;
  logs: DailyLog[];
  userProfile: UserProfile | null;
}

export const MonthlyReportDocument = ({ report, logs, userProfile }: MonthlyReportDocumentProps) => (
  <Document
    title={`Monthly Report - ${report.month}`}
    author={userProfile?.displayName || 'AttachFlow User'}
  >
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Monthly Attachment Report</Text>
        <Text style={styles.subtitle}>{report.month}</Text>
        <Text style={styles.subtitle}>Student: {userProfile?.displayName || 'N/A'}</Text>
      </View>

      <View style={styles.table}>
        {/* Table Header */}
        <View style={styles.tableRow}>
          <View style={styles.tableColHeader}>
            <Text style={styles.tableCellHeader}>Date</Text>
          </View>
          <View style={styles.tableColHeader}>
            <Text style={styles.tableCellHeader}>Log Entry</Text>
          </View>
        </View>

        {/* Table Body */}
        {logs.sort((a,b) => a.date.seconds - b.date.seconds).map((log) => (
          <View style={styles.tableRow} key={log.id}>
            <View style={styles.logDateCell}>
              <Text style={styles.tableCell}>{format(log.date.toDate(), 'EEEE, MMMM d, yyyy')}</Text>
            </View>
            <View style={styles.logContentCell}>
              <Text style={styles.tableCell}>{log.content}</Text>
            </View>
          </View>
        ))}
      </View>
      
      <Text style={styles.footer}>
        Report generated by AttachFlow on {format(new Date(), 'MMMM d, yyyy')}
      </Text>
    </Page>
  </Document>
);
